### ISSUE TITLE
Facing the build issue 

### ISSUE THREAD

**Issue by senthilpeace** [Minio-io/minio#163]
Below is the snapshot of the build issue...

vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$ pwd
/home/vagrant/mygo/src/github.com/minio-io/minio
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$ make
Checking if proper environment variables are set.. Done
Using GOPATH=/home/vagrant/mygo and GOROOT=/home/vagrant/local/go
Checking dependencies for Minio.. Done
Installed godep
Installed cover
  ---> Building src/gf-vect-dot-prod-avx2.asm
src/gf-vect-dot-prod-avx2.asm:133: error: undefined symbol `gf_vect_dot_prod_avx2.return_fail' (first use)
src/gf-vect-dot-prod-avx2.asm:133: error:  (Each undefined symbol is reported only once.)
src/gf-vect-dot-prod-avx2.asm:137: error: instruction expected after label
src/gf-vect-dot-prod-avx2.asm:149: error: instruction expected after label
src/gf-vect-dot-prod-avx2.asm:150: error: instruction expected after label
src/gf-vect-dot-prod-avx2.asm:165: error: undefined symbol `vperm2i128.next_vect' (first use)
src/gf-vect-dot-prod-avx2.asm:170: error: undefined symbol `vperm2i128.loop32' (first use)
make[1]: *** [src/gf-vect-dot-prod-avx2.o] Error 1
make: *** [build-erasure] Error 2
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$

Please advice how to resolve this build issue.

**Comment by harshavardhana** [comment]
@senthilpeace - do you have 'yasm' installed?

**Comment by harshavardhana** [comment]
```sh
# cd /home/vagrant/mygo/src/github.com/minio-io/minio
# git pull --rebase
# make
```

Should tell us properly about the 'yasm' issue for now

**Comment by senthilpeace** [comment]
Here is the info that you have asked...
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$ uname -a
Linux hanlon 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$ yasm --version
yasm 1.1.0.2352
Compiled on Jun 10 2011.
Copyright (c) 2001-2010 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$ grep avx2 /proc/cpuinfo
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$

**Am running the Ubuntu VM's using the Virtual Box on Mac OS host m/c. And also noticed that not able to find out avx2 instruction set**

vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$ cat /proc/cpuinfo
*
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
stepping	: 1
microcode	: 0x19
cpu MHz		: 2226.031
cache size	: 6144 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm
bogomips	: 4452.06
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
stepping	: 1
microcode	: 0x19
cpu MHz		: 2226.031
cache size	: 6144 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm
bogomips	: 4429.68
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
*
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$

**Comment by senthilpeace** [comment]
**Though I've rebase the latest code and installed the yasm, it's not working, getting the below error**

*vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$ make
Checking if proper environment variables are set.. Done
Using GOPATH=/home/vagrant/mygo and GOROOT=/home/vagrant/local/go
Checking dependencies for Minio.. ERROR

The following build tools are missing:

**  yasm(elf64 support) **

Please install them
$ sudo apt-get install  yasm(elf64 support)

make: *** [checkdeps] Error 1
vagrant@hanlon:~/mygo/src/github.com/minio-io/minio$*

**Comment by harshavardhana** [comment]
This is exactly what i wanted to know sorry to hear that, the issue is as i explained earlier about the lack of support of instruction sets with in yasm version 1.1.0. Yasm on Ubuntu 12.04 lacks AVX2 support,  only yasm release http://yasm.tortall.net/releases/Release1.2.0.html onwards has this support

if possible you could try installing the new version of 'yasm' and replace your system version?

**Comment by senthilpeace** [comment]
@harshavardhana : Thanks for your response. Finally build is got succeed on Ubuntu 14.04.1 LTS platform.

**Comment by harshavardhana** [comment]
> @harshavardhana : Thanks for your response. Finally build is got succeed on Ubuntu 14.04.1 LTS platform.

Glad to hear that

**Comment by harshavardhana** [comment]
Closing this issue.. yasm 1.2.0 minimum required - https://github.com/Minio-io/minio/commit/35fa6671645005b544cad3264c9c350ebba2ead7
